RCF-203,205 & 211
mosip/android-registration-client pull request #163
Opened 2023-08-29 10:31 UTC by aviral-mishra-hunter

[RCF-203] [RCF-205] [RCF-211]

2023-09-04 06:09 UTC, jainhitesh9998 requested changes

2023-09-04 06:09 UTC, jainhitesh9998 commented on lib/ui/login_page.dart
> +// ignore_for_file: use_build_context_synchronously
any reason for ignoring lint rules here

2023-09-06 05:16 UTC, developer-aditya commented on android/clientmanager/src/main/java/io/mosip/registration/clientmanager/entity/Registration.java
> +        return packetId + " " + (serverStatus == null ? clientStatus : serverStatus);
I was trying to log all packet Id with status in single line. we can change it back to \n

2023-09-06 06:48 UTC, developer-aditya commented on lib/platform_android/packet_service_impl.dart
> +      debugPrint('PacketAuthenticationApi call failed!');
Log doesn't show up when we run the app in release mode.

2023-09-06 06:49 UTC, developer-aditya commented on android/app/src/main/java/io/mosip/registration_client/MainActivity.java
> +            registrationList = packetService.getRegistrationsByStatus("CREATED");
Okay, will work on this

2023-09-12 04:38 UTC, jainhitesh9998 approved these changes

2023-09-12 04:39 UTC, merged