Transliteration
mosip/android-registration-client pull request #222
Opened 2023-12-01 09:25 UTC by developer-aditya

[RCF-264](https://mosip.atlassian.net/browse/RCF-264) - Transliteration for every textbox having multi language input added

2023-12-05 04:41 UTC, jainhitesh9998 requested changes
can we segregrate the transliteration logic

2023-12-05 04:41 UTC, jainhitesh9998 commented on android/app/src/main/java/io/mosip/registration_client/api_services/TransliterationApi.java
can we segregrate the transliteration logic 

have a similar interface and implementation separated and use pigeon api's just to call out the service
https://github.com/mosip/commons/blob/master/kernel/kernel-core/src/main/java/io/mosip/kernel/core/transliteration/spi/Transliteration.java

2023-12-06 05:34 UTC, developer-aditya commented on android/app/src/main/java/io/mosip/registration_client/api_services/TransliterationApi.java
okay sure

2023-12-11 13:01 UTC, jainhitesh9998 commented on android/transliterationmanager/src/test/java/io/mosip/registration/transliterationmanager/ExampleUnitTest.java
we should have relevent test case for the libraries, not example ones

2023-12-12 02:02 UTC, jainhitesh9998 requested changes

2023-12-12 02:02 UTC, jainhitesh9998 commented on android/transliterationmanager/src/test/java/io/mosip/registration/transliterationmanager/TransliterationServiceUnitTest.java
> +    TransliterationServiceImpl transliterationService;
we should initialize interface, not the impl here

2023-12-12 04:40 UTC, jainhitesh9998 approved these changes

2023-12-12 04:40 UTC, merged