MOSIP-31687
mosip/android-registration-client pull request #298
Opened 2024-03-18 12:09 UTC by jayesh12234

2024-04-19 11:43 UTC, anup-nehe commented on androidReg-clientTest/src/main/java/regclient/pages/arabic/DemographicDetailsPageArabic.java
> +	private WebElement foreignerValueFromDropdown;
use camelcase

2024-04-19 12:21 UTC, anup-nehe requested changes

2024-04-19 12:21 UTC, anup-nehe commented on androidReg-clientTest/src/test/java/androidTestCases/logintest.java
> +		// assertTrue(registrationTasksPage.isMasterDataSyncCompletedDisplayed(),"Verify if masterData sync should be completed successfully");
remove unwanted code

2024-04-19 12:21 UTC, anup-nehe commented on androidReg-clientTest/src/test/java/androidTestCases/logintest.java
>  		//assertFalse(loginPage.isLoginButtonEnabled(),"verify if the login button is disable without entering password");
remove unwanted code

2024-04-24 09:44 UTC, kamalsinghthoughtworks approved these changes

2024-05-02 19:17 UTC, merged