[RCF-69] Forgot Password functionality
mosip/android-registration-client pull request #418
Opened 2024-07-26 05:04 UTC by SachinPremkumar

[RCF-69]

2024-08-07 14:32 UTC, jainhitesh9998 requested changes

2024-08-07 14:32 UTC, jainhitesh9998 commented on android/build.gradle
> +    serverForgotPasswordURL = "\"iam.qa-platform1.mosip.net\""
i think we get this value from server side config, we can check this once

2024-08-07 14:32 UTC, jainhitesh9998 commented on android/app/src/main/java/io/mosip/registration_client/api_services/AuthenticationApi.java
> +        String response = "https://"+ BuildConfig.FORGOT_PASSWORD_URL +"/auth/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https%3A%2F%2F"+ BuildConfig.FOR
adding static client id and nonce, response code is not recommended

2025-01-13 11:29 UTC, SachinPremkumar commented on android/build.gradle
> +    serverForgotPasswordURL = "\"iam.qa-platform1.mosip.net\""
Updated.

2025-01-13 11:31 UTC, SachinPremkumar commented on android/app/src/main/java/io/mosip/registration_client/api_services/AuthenticationApi.java
> +        String response = "https://"+ BuildConfig.FORGOT_PASSWORD_URL +"/auth/realms/master/protocol/openid-connect/auth?client_id=security-admin-console&redirect_uri=https%3A%2F%2F"+ BuildConfig.FOR
now we are using from config properties.

2025-01-15 10:22 UTC, jainhitesh9998 requested changes

2025-01-15 10:22 UTC, jainhitesh9998 commented on android/app/src/main/java/io/mosip/registration_client/api_services/AuthenticationApi.java
> +        System.out.println("<======forgot password url======>"+this.globalParamRepository.getCachedStringForgotPassword());
can you remove this, we should not have sysout in application, use logger instead

2025-01-15 10:22 UTC, jainhitesh9998 commented on android/app/src/main/java/io/mosip/registration_client/api_services/AuthenticationApi.java
> +        System.out.println("<======forgot password url======>"+this.globalParamRepository.getCachedStringForgotPassword());
also this value should not be logged

2025-01-15 10:22 UTC, jainhitesh9998 commented on lib/ui/widgets/password_component.dart
> +        // ),
can you removed the commented conmponent

2025-01-15 11:54 UTC, SachinPremkumar commented on android/app/src/main/java/io/mosip/registration_client/api_services/AuthenticationApi.java
> +        System.out.println("<======forgot password url======>"+this.globalParamRepository.getCachedStringForgotPassword());
I removed system.out.prtintln

2025-01-15 11:54 UTC, SachinPremkumar commented on lib/ui/widgets/password_component.dart
> +        // ),
removed

2025-01-16 03:46 UTC, jainhitesh9998 approved these changes

2025-01-16 03:47 UTC, merged