AudioManager
mosip/android-registration-client pull request #44
Opened 2022-05-24 06:53 UTC by BioEnable-bit

1. AuditManagerSerivceImpl is created 
2. AuditManagerService is created 
3. AuditDao is created

2022-06-03 12:35 UTC, anshulv1401 requested changes
Please check the comments for the changes required

2022-06-03 12:35 UTC, anshulv1401 commented on client/clientmanager/src/main/java/io/mosip/registration/clientmanager/spi/audit/AuditManagerSerivceImpl.java
> +package io.mosip.registration.clientmanager.spi.audit;
Impl classes should be added directly under package: io.mosip.registration.clientmanager.service

2022-06-03 12:35 UTC, anshulv1401 commented on client/clientmanager/src/main/java/io/mosip/registration/clientmanager/spi/audit/builder/AuditRequestBuilder.java
> +import org.springframework.stereotype.Service;
invalid imports must be removed

2022-06-03 12:35 UTC, anshulv1401 commented on client/clientmanager/src/main/java/io/mosip/registration/clientmanager/spi/audit/request/AuditRequestDto.java
> +package io.mosip.registration.clientmanager.spi.audit.request;
dtos must be added under package : io.mosip.registration.clientmanager.dto

2022-06-03 12:35 UTC, anshulv1401 commented on client/clientmanager/src/main/java/io/mosip/registration/clientmanager/util/restclient/AuthTokenUtilService.java
> +//package io.mosip.registration.clientmanager.util.restclient;
this file can be deleted

2022-06-03 12:35 UTC, anshulv1401 commented on client/clientmanager/src/main/java/io/mosip/registration/clientmanager/util/restclient/RequestHTTPDTO.java
> +//package io.mosip.registration.clientmanager.util.restclient;
this file can be deleted

2022-06-03 12:35 UTC, anshulv1401 commented on client/clientmanager/src/main/java/io/mosip/registration/clientmanager/util/restclient/RestClientUtil.java
> +//`package io.mosip.registration.clientmanager.util.restclient;
this file can be deleted

2022-06-03 12:35 UTC, anshulv1401 commented on client/clientmanager/src/main/java/io/mosip/registration/clientmanager/util/restclient/ServiceDelegateUtil.java
> +//package io.mosip.registration.clientmanager.util.restclient;
this file can be deleted

2022-06-04 05:52 UTC, BioEnable-bit reviewed
@anshulv1401 Given changes are done. Please check at your side.

2022-06-09 06:24 UTC, ase-101 commented
Closing as the PR is outdated.

2022-06-09 06:24 UTC, closed without merging